### ISSUE TITLE
Block VPN connections using the CCD disable option.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-ui#11]
- [x] New option menu over a client VPN connection for block such VPN.
- [x] If the user selects this option, FWCloud-UI will add the `disable` config option to the CCD configuration of the VPN and send the API call for update the VPN configuration.
- [x] Next it will request the installation of the VPN.
- [x] Display the VPN with a forbidden symbol over the VPN icon for indicate that it is disabled.

**Comment by fperezgaliana** [comment]
- [ ] We need to have a `disabled` flag in the tree to manage this option
