### ISSUE TITLE
Improve VPN certificate name generation

### ISSUE THREAD

**Issue by vrrc** [soltecsis/fwcloud-ui#43]
When creating a certificate for a VPN using the included wizard, it would be nice if:

- The blue "wizard" button that's on the right should be on the left. If you don't create certificates too often it's easy to miss that you can enable/disable the assisted certificate creation which changes the name of the about to be created certificate.
- When using the wizard, if any field is empty, don't add hyphens in the name. I.E. if just filling name and surname, the wizard creates a name like "ORGANIZATION---name.surname-00" instead of "ORGANIZATION-name.surname-00".
- Finally, the "wizard" button/feature could be renamed to something like "name patterns", so new patterns can be added. Even a feature to add user defined patterns could be useful here.

**Comment by cmunyoz** [comment]
Thank you very much for your suggestions. Feedback from the community is always appreciated.
We will analyze it and decide if we incorporate them in the next release.
