### ISSUE TITLE
IPtables Compile/install command fail

### ISSUE THREAD

**Issue by quinhn** [soltecsis/fwcloud-ui#66]
Hi Team,
I'm facing error when compile/install iptables rules to server.
![Screenshot from 2023-07-17 16-24-18](https://github.com/soltecsis/fwcloud-ui/assets/77380031/a1ddc302-4326-4bf2-9c04-d3f64fbe8bf0)
Could you please help to change the iptables install command to **/usr/bin/sh -c 'if [ -d /etc/fwcloud ]; then sh  /etc/fwcloud/fwcloud.sh start; else sh  /config/scripts/post-config.d/fwcloud.sh start; fi'**
Thanks.

**Comment by cmunyoz** [comment]
Which communication method are you using for manage your firewall (ssh or FWCloud-Agent)?

**Comment by quinhn** [comment]
Hi @cmunyoz,
I'm using SSH to manage filewalls and FWCloud Docker version.
Thanks.

**Comment by cmunyoz** [comment]
I think that is better that we solve this issue by means of the FWCloud forum:  https://forum.fwcloud.net/
Please, can you register on it and submit the issue?

Thanks.

**Comment by quinhn** [comment]
sure, will do.
Thanks

**Comment by cmunyoz** [comment]
Great, thank you very much.
