### ISSUE TITLE
Copy-paste not working between firewalls

### ISSUE THREAD

**Issue by tolgaulas** [soltecsis/fwcloud-ui#78]
Documentation described https://fwcloud-ui-doc.fwcloud.net/docs/Sections/Policy/#copy-rule is not working (tried both on chrome and firefox latest) in between different firewalls. Copy icon appears when copied but disappears when switched the firewall. However it works withing the same firewall. May be usefull to notify this limitation. (Or better implement it as a feature? :))

**Comment by cmunyoz** [comment]
This is a bug, it worked before.
We are going to fix it and generate a patch release that solves it.

**Comment by soltecsis-jfernandez** [comment]
Hi Mr. Ulas, 
What do you need to copy/paste exactly? Rule from 1 policy firewall to another diferent policy firewall, or objects from one policy firewall to another diferent policy (from another firewall).

**Comment by soltecsis-jfernandez** [comment]
> Documentation described https://fwcloud-ui-doc.fwcloud.net/docs/Sections/Policy/#copy-rule is not working (tried both on chrome and firefox latest) in between different firewalls. Copy icon appears when copied but disappears when switched the firewall. However it works withing the same firewall. May be usefull to notify this limitation. (Or better implement it as a feature? :))

Hi Mr. Ulas,
What do you need to copy/paste exactly? Rule from 1 policy firewall to another diferent policy firewall, or objects from one policy firewall to another diferent policy (from another firewall).
